services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  app:
    build:
      context: .
    container_name: flask_app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/mydatabase"
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
